apiVersion: v1
kind: Secret
metadata:
  name: aegis-app
  labels:
    {{- include "aegis.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.postgres.password | quote }}
  jwt-secret: {{ .Values.shortener.jwtSecret | quote }}
